name: speech
description: A new Flutter project.


publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
#  sdk: '>=2.12.0 <=3.0.6'
  sdk: '>=2.19.1 <3.0.0'


dependencies:
  flutter:
    sdk: flutter
  easy_localization: ^3.0.3
  sizer: ^2.0.15
  dropdown_button2:
  flutter_verification_code: ^1.1.6
  timer_count_down: ^2.2.2
  fluid_bottom_nav_bar: ^1.4.0
  stylish_bottom_bar: ^1.0.3
  dropdown_textfield: ^1.0.8
#  file_picker: ^6.0.0
  file_picker:
  image_picker: ^1.0.4
  record: ^4.4.4
#  audioplayers: ^5.2.0
  audioplayers:
  flutter_svg:
  quds_popup_menu: ^0.0.1+1
  context_menus: ^1.0.2
  custom_pop_up_menu: ^1.2.4
  flutter_keyboard_visibility: ^5.4.1
  dio: ^5.3.3
  logger: ^2.0.2+1
  get_it: ^7.6.0
  logging: ^1.1.0
  provider: ^6.0.4
  shared_preferences:
  fluttertoast: ^8.2.2
  firebase_core: ^2.24.2
  rounded_loading_button: ^2.1.0
  cupertino_icons: ^1.0.2
  cached_network_image: ^3.3.0
  path_provider: ^2.0.2
  permission_handler: ^8.0.0+2
  material_dialogs: ^1.1.4
  firebase_auth: ^4.15.3
  url_launcher: ^6.1.6
  image_gallery_saver: ^2.0.3

  modal_bottom_sheet:
    git:
      url: https://github.com/danReynolds/modal_bottom_sheet.git
      path: modal_bottom_sheet
dev_dependencies:
  flutter_test:
    sdk: flutter



  flutter_lints: ^2.0.0


flutter:


  uses-material-design: true


  assets:
    - assets/images/
    - assets/images/svg/
    - assets/localizations/



  fonts:
    - family: DIN Next LT W23
      fonts:
        - asset: assets/fonts/din-next-lt-w23-regular.ttf

